name: Sign release artifacts

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Specify the Version name eg: 2201.6.0, 2201.6.0-rc1'
        required: true
        default: ''
      isPreRelease:
        description: 'Tag created is a pre-release tag'
        required: true
        default: 'false'
      preReleaseSuffix:
        description: 'The text that will be suffixed to the Git tag. e.g., rc1'
        required: false
        default: ''

permissions:
  id-token: write 
  contents: write

jobs:
  sign-release:
    name: Sign release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: cosign-installer
        uses: sigstore/cosign-installer@v3.0.3
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install GitHub CLI
        run: |
          npm install -g github-cli
      # - name: Retrieve Git Tag
      #   id: retrieve-tag
      #   env:
      #     GH_TOKEN : ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     release=$(gh release view --json tagName -R Miranlfk/ballerina-distribution --jq '.tagName' | sed 's/^v//')
      #     echo "::set-output name=tag::$release"
      #     tag=$(gh release view --json tagName -R Miranlfk/ballerina-distribution --jq '.tagName')
      #     echo "::set-output name=release::$tag"
      - name: Retrieve MacOS Installer
        run:
          |
          wget https://github.com/Miranlfk/ballerina-distribution/releases/download/v${{ github.event.inputs.versionName }}/ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-x64.pkg
      - name: Sign the MacOS Installer
        run: |
          cosign sign-blob ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-x64.pkg --output-certificate ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-x64.pkg.pem --output-signature ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-x64.pkg.sig --yes
      - name: Verify the MacOS Installer
        run: |
          cosign verify-blob ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-x64.pkg --certificate ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-x64.pkg.pem --signature ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-x64.pkg.sig --certificate-identity=https://github.com/Miranlfk/ballerina-distribution/.github/workflows/sign-installers.yml@${{ github.ref }} --certificate-oidc-issuer=https://token.actions.githubusercontent.com 
      - name: Retrieve MacOS-ARM Installer
        run:
          |
          wget https://github.com/Miranlfk/ballerina-distribution/releases/download/v${{ github.event.inputs.versionName }}/ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-arm-x64.pkg
      - name: Sign the MacOS-ARM Installer
        run: |
          cosign sign-blob ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-arm-x64.pkg --output-certificate ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-arm-x64.pkg.pem --output-signature ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-arm-x64.pkg.sig --yes
      - name: Verify the MacOS-ARM Installer
        run: |
          cosign verify-blob ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-arm-x64.pkg --certificate ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-arm-x64.pkg.pem --signature ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-arm-x64.pkg.sig --certificate-identity=https://github.com/Miranlfk/ballerina-distribution/.github/workflows/sign-installers.yml@${{ github.ref }} --certificate-oidc-issuer=https://token.actions.githubusercontent.com
      - name: Retrieve Windows Installer
        run:
          |
          wget https://github.com/Miranlfk/ballerina-distribution/releases/download/v${{ github.event.inputs.versionName }}/ballerina-${{ github.event.inputs.versionName }}-swan-lake-windows-x64.msi
      - name: Sign the Windows Installer
        run: |
          cosign sign-blob ballerina-${{ github.event.inputs.versionName }}-swan-lake-windows-x64.msi --output-certificate ballerina-${{ github.event.inputs.versionName }}-swan-lake-windows-x64.msi.pem --output-signature ballerina-${{ github.event.inputs.versionName }}-swan-lake-windows-x64.msi.sig --yes
      - name: Verify the Windows Installer
        run: |
          cosign verify-blob ballerina-${{ github.event.inputs.versionName }}-swan-lake-windows-x64.msi --certificate ballerina-${{ github.event.inputs.versionName }}-swan-lake-windows-x64.msi.pem --signature ballerina-${{ github.event.inputs.versionName }}-swan-lake-windows-x64.msi.sig --certificate-identity=https://github.com/Miranlfk/ballerina-distribution/.github/workflows/sign-installers.yml@${{ github.ref }} --certificate-oidc-issuer=https://token.actions.githubusercontent.com
      - name: Upload Installers' Verification Files
        env:
          GH_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ${{ github.event.inputs.isPreRelease }} == 'true'; then tagName=$(echo "$${{ github.event.inputs.versionName }}" | sed 's/$/ -${{ github.event.inputs.preReleaseSuffix }}/'); else tagName=${{ github.event.inputs.versionName }}; fi
          gh release upload v$tagName ./ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-x64.pkg.pem --clobber
          gh release upload v$tagName ./ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-x64.pkg.sig --clobber
          gh release upload v$tagName ./ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-arm-x64.pkg.pem --clobber
          gh release upload v$tagName ./ballerina-${{ github.event.inputs.versionName }}-swan-lake-macos-arm-x64.pkg.sig --clobber
          gh release upload v$tagName ./ballerina-${{ github.event.inputs.versionName }}-swan-lake-windows-x64.msi.pem --clobber
          gh release upload v$tagName ./ballerina-${{ github.event.inputs.versionName }}-swan-lake-windows-x64.msi.sig --clobber
